//MONGOOSE
const { Schema, model } = require('mongoose');

//I believe objectID is autogenerated for each
const CharacterSchema = new Schema({
  name: {
    type: String,
    trim: true,
    required: 'Username is Required',
  },
  hitPoints: {
    type: Number,
    trim: true,
  },
  attack: {
    type: Number,
    trim: true,
  },
  experience: {
    type: Number,
    trim: true,
  },
  level: {
    type: Number,
    trim: true,
    required: 'Name is Required',
  },
});

const Character = model('Character', CharacterSchema);

module.exports = Character;

/* SQL 
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection.js');
class Character extends Model {}

Character.init(
  {
    id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
      },
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'user',
        key: 'id',
      },
      defaultValue: 0,
    },
    hp: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    attack: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    // TODO: add level
    // TODO: add character position (x,y)? 
  },
  {
    sequelize,
    timestamps: false,
    freezeTableName: true,
    underscored: true,
    modelName: 'character',
  }
);

module.exports = Character;
*/
