//MONGOOSE
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//I believe objectID is autogenerated for each
const QuestionSchema = new Schema({
  id: {
    type: Number,
    trim: true,
    required: 'id is Required',
  },
  question: {
    type: String,
    trim: true,
    required: 'Question is Required',
  },
  description: {
    type: String,
    trim: true,
  },
  answers: {
    type: Object,
    trim: true,
    required: 'answers Required',
  },
  multiple_correct_answers: {
    type: Boolean,
  },
  correct_answers: {
    type: Object,
    trim: true,
    required: 'correct answers Required',
  },
  correct_answer: {
    type: String,
    trim: true,
    required: 'correct answer Required',
  },
  explanation: {
    type: String,
    trim: true,
  },
  tip: {
    type: String,
    trim: true,
  },
  tags: {
    type: Array,
    trim: true,
  },
  category: {
    type: String,
    trim: true,
  },
  difficulty: {
    type: String,
    trim: true,
  },
});

const Questions = mongoose.model('Question', QuestionSchema);

module.exports = Questions;
